# -*- coding: utf-8 -*-
"""TUGAS_ML_G1A024103_M. NABIL FITTERZON.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IhQlhTGwJLQ6yk7cC5BOhhOYJLcMgDwO
"""

import numpy as np
import pandas as pd
import matplotlib
import matplotlib.pyplot as plt
import scipy
import sklearn

print("NumPy:", np.__version__)
print("Pandas:", pd.__version__)
print("Matplotlib:", matplotlib.__version__)
print("SciPy:", scipy.__version__)
print("Scikit-learn:", sklearn.__version__)

!pip install mglearn

import mglearn
import matplotlib.pyplot as plt

mglearn.plots.plot_knn_classification(n_neighbors=1)
plt.show()

from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
import mglearn

# Membuat dataset forge
X, y = mglearn.datasets.make_forge()

# Membagi data menjadi data training dan testing
X_train, X_test, y_train, y_test = train_test_split(
    X, y, random_state=0
)

# Membuat model KNN dengan 3 tetangga
clf = KNeighborsClassifier(n_neighbors=3)

# Melatih model
clf.fit(X_train, y_train)

# Menampilkan prediksi
print("Prediksi:", clf.predict(X_test))

# Menampilkan akurasi
print("Akurasi:", clf.score(X_test, y_test))

from sklearn.linear_model import LogisticRegression
from sklearn.svm import LinearSVC

X, y = mglearn.datasets.make_forge()

fig, axes = plt.subplots(1, 2, figsize=(10, 3))

for model, ax in zip([LinearSVC(), LogisticRegression()], axes):
    clf = model.fit(X, y)

    mglearn.plots.plot_2d_separator(
        clf, X, fill=False, eps=0.5,
        ax=ax, alpha=.7
    )

    mglearn.discrete_scatter(X[:, 0], X[:, 1], y, ax=ax)

    ax.set_title("{}".format(clf.__class__.__name__))
    ax.set_xlabel("Feature 0")
    ax.set_ylabel("Feature 1")

axes[0].legend()
plt.show()

mglearn.plots.plot_linear_svc_regularization()
plt.show()

from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import train_test_split
import mglearn

X, y = mglearn.datasets.make_forge()

X_train, X_test, y_train, y_test = train_test_split(
    X, y, random_state=0
)

clf = GaussianNB()
clf.fit(X_train, y_train)

print("Prediksi:", clf.predict(X_test))
print("Akurasi:", clf.score(X_test, y_test))

from sklearn.tree import DecisionTreeClassifier
import mglearn
import matplotlib.pyplot as plt

X, y = mglearn.datasets.make_forge()

tree = DecisionTreeClassifier(random_state=0)
tree.fit(X, y)

print("Akurasi:", tree.score(X, y))

from sklearn.tree import export_graphviz
import graphviz

export_graphviz(
    tree,
    out_file="tree.dot",
    class_names=["class 0", "class 1"],
    feature_names=["feature 0", "feature 1"],
    impurity=False,
    filled=True
)

with open("tree.dot") as f:
    dot_graph = f.read()

graphviz.Source(dot_graph)

from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
import mglearn

X, y = mglearn.datasets.make_forge()

X_train, X_test, y_train, y_test = train_test_split(
    X, y, random_state=0
)

forest = RandomForestClassifier(
    n_estimators=5,
    random_state=2
)

forest.fit(X_train, y_train)

print("Prediksi:", forest.predict(X_test))
print("Akurasi:", forest.score(X_test, y_test))

import matplotlib.pyplot as plt

fig, axes = plt.subplots(2, 3, figsize=(15, 10))

for i, (ax, tree) in enumerate(
    zip(axes.ravel(), forest.estimators_)
):
    ax.set_title("Tree {}".format(i + 1))
    mglearn.plots.plot_tree_partition(
        X_train, y_train, tree, ax=ax
    )

mglearn.plots.plot_2d_separator(
    forest, X_train, fill=True, ax=axes[-1, -1], alpha=.4
)
mglearn.discrete_scatter(
    X_train[:, 0], X_train[:, 1], y_train,
    ax=axes[-1, -1]
)

plt.show()

from sklearn.svm import SVC
import mglearn
import matplotlib.pyplot as plt

X, y = mglearn.tools.make_handcrafted_dataset()

svm = SVC(kernel='rbf', C=10, gamma=0.1).fit(X, y)

mglearn.plots.plot_2d_separator(svm, X, eps=.5)

mglearn.discrete_scatter(X[:, 0], X[:, 1], y)

# Menampilkan support vectors
sv = svm.support_vectors_

sv_labels = svm.dual_coef_.ravel() > 0

mglearn.discrete_scatter(
    sv[:, 0], sv[:, 1],
    sv_labels,
    s=15,
    markeredgewidth=3
)

plt.xlabel("Feature 0")
plt.ylabel("Feature 1")
plt.show()

from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import train_test_split
import mglearn

X, y = mglearn.datasets.make_forge()

X_train, X_test, y_train, y_test = train_test_split(
    X, y, random_state=0
)

mlp = MLPClassifier(
    solver='lbfgs',
    random_state=0
)

mlp.fit(X_train, y_train)

print("Prediksi:", mlp.predict(X_test))
print("Akurasi:", mlp.score(X_test, y_test))

import matplotlib.pyplot as plt

mglearn.plots.plot_2d_separator(
    mlp, X, fill=True, alpha=.3
)

mglearn.discrete_scatter(
    X[:, 0], X[:, 1], y
)

plt.xlabel("Feature 0")
plt.ylabel("Feature 1")
plt.show()

from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler

# load dan split dataset
cancer = load_breast_cancer()

X_train, X_test, y_train, y_test = train_test_split(
    cancer.data,
    cancer.target,
    random_state=1
)

print("Training set:", X_train.shape)
print("Test set:", X_test.shape)

# membuat scaler
scaler = MinMaxScaler()

# menghitung minimum dan maksimum dari data training
scaler.fit(X_train)

# transform data training
X_train_scaled = scaler.transform(X_train)

print("\nBentuk data setelah scaling:", X_train_scaled.shape)
print("\nMinimum sebelum scaling:")
print(X_train.min(axis=0))

print("\nMaksimum sebelum scaling:")
print(X_train.max(axis=0))

print("\nMinimum setelah scaling:")
print(X_train_scaled.min(axis=0))

print("\nMaksimum setelah scaling:")
print(X_train_scaled.max(axis=0))

from sklearn.datasets import load_breast_cancer
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
import matplotlib.pyplot as plt

# Load dataset
cancer = load_breast_cancer()

# Standardisasi data
X_scaled = StandardScaler().fit_transform(cancer.data)

# Membuat PCA dengan 2 komponen
pca = PCA(n_components=2)

# Transformasi data
X_pca = pca.fit_transform(X_scaled)

print("Bentuk data sebelum PCA:", cancer.data.shape)
print("Bentuk data setelah PCA:", X_pca.shape)
print("Explained variance ratio:")
print(pca.explained_variance_ratio_)

plt.figure(figsize=(8, 6))

plt.scatter(
    X_pca[:, 0],
    X_pca[:, 1],
    c=cancer.target,
    alpha=0.7
)

plt.xlabel("First principal component")
plt.ylabel("Second principal component")
plt.title("PCA - Breast Cancer Dataset")

plt.show()

from sklearn.datasets import fetch_lfw_people
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt

# Load dataset wajah
people = fetch_lfw_people(
    min_faces_per_person=20,
    resize=0.7
)

image_shape = people.images[0].shape

# Ubah gambar menjadi data 2D
X_people = people.data
y_people = people.target

# Bagi data training dan test
X_train, X_test, y_train, y_test = train_test_split(
    X_people,
    y_people,
    stratify=y_people,
    random_state=0
)

print("X_train:", X_train.shape)
print("X_test:", X_test.shape)
print("Image shape:", image_shape)

from sklearn.decomposition import NMF

# Membuat NMF dengan 15 komponen
nmf = NMF(
    n_components=15,
    random_state=0
)

nmf.fit(X_train)

X_train_nmf = nmf.transform(X_train)
X_test_nmf = nmf.transform(X_test)

print("X_train_nmf:", X_train_nmf.shape)
print("X_test_nmf:", X_test_nmf.shape)

fig, axes = plt.subplots(
    3, 5,
    figsize=(15, 12),
    subplot_kw={'xticks': (), 'yticks': ()}
)

for i, (component, ax) in enumerate(
    zip(nmf.components_, axes.ravel())
):
    ax.imshow(component.reshape(image_shape))
    ax.set_title("{}. component".format(i))

plt.show()

from sklearn.datasets import load_digits
from sklearn.manifold import TSNE
import matplotlib.pyplot as plt

digits = load_digits()

tsne = TSNE(random_state=42)

digits_tsne = tsne.fit_transform(digits.data)

print("Bentuk data sebelum t-SNE:", digits.data.shape)
print("Bentuk data setelah t-SNE:", digits_tsne.shape)

plt.figure(figsize=(10, 10))

plt.scatter(
    digits_tsne[:, 0],
    digits_tsne[:, 1],
    c=digits.target,
    cmap="tab10",
    s=10
)

plt.colorbar()
plt.xlabel("t-SNE 1")
plt.ylabel("t-SNE 2")
plt.title("t-SNE pada Dataset Digits")

plt.show()

from sklearn.cluster import KMeans

kmeans = KMeans(n_clusters=10, random_state=0)

kmeans.fit(X_train)

print("Cluster yang terbentuk:")
print(kmeans.labels_[:20])

import numpy as np

print("Jumlah data pada setiap cluster:")
print(np.bincount(kmeans.labels_))

from sklearn.decomposition import PCA
import matplotlib.pyplot as plt

pca = PCA(n_components=2, random_state=0)

X_train_pca = pca.fit_transform(X_train)

plt.figure(figsize=(10, 7))

plt.scatter(
    X_train_pca[:, 0],
    X_train_pca[:, 1],
    c=kmeans.labels_,
    s=10
)

plt.xlabel("PCA 1")
plt.ylabel("PCA 2")
plt.title("k-Means Clustering")

plt.show()

from sklearn.datasets import make_moons
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import AgglomerativeClustering
import matplotlib.pyplot as plt

X, y = make_moons(n_samples=200, noise=0.05, random_state=0)

# Rescale data
scaler = StandardScaler()
scaler.fit(X)
X_scaled = scaler.transform(X)

# Agglomerative Clustering
agg = AgglomerativeClustering(n_clusters=2)

clusters = agg.fit_predict(X_scaled)

print("Cluster hasil Agglomerative:")
print(clusters[:20])

plt.figure(figsize=(8, 6))

plt.scatter(
    X_scaled[:, 0],
    X_scaled[:, 1],
    c=clusters,
    s=60
)

plt.xlabel("Feature 0")
plt.ylabel("Feature 1")
plt.title("Agglomerative Clustering")

plt.show()

from sklearn.cluster import DBSCAN
import numpy as np

# DBSCAN dengan parameter default
dbscan = DBSCAN()

labels = dbscan.fit_predict(X_pca)

print("Unique labels:", np.unique(labels))

dbscan = DBSCAN(min_samples=3)

labels = dbscan.fit_predict(X_pca)

print("Unique labels:", np.unique(labels))

dbscan = DBSCAN(min_samples=3, eps=15)

labels = dbscan.fit_predict(X_pca)

print("Unique labels:", np.unique(labels))

print(
    "Number of points per cluster:",
    np.bincount(labels + 1)
)

dbscan = DBSCAN(min_samples=3, eps=7)

labels = dbscan.fit_predict(X_pca)

print("Unique labels:", np.unique(labels))
print("Number of points per cluster:", np.bincount(labels + 1))

from sklearn.decomposition import PCA
from sklearn.cluster import DBSCAN
import numpy as np
import matplotlib.pyplot as plt

# PCA pada X_train
pca = PCA(n_components=100, whiten=True, random_state=0)
X_train_pca = pca.fit_transform(X_train)

print("X_train:", X_train.shape)
print("X_train_pca:", X_train_pca.shape)

# DBSCAN
dbscan = DBSCAN(min_samples=3, eps=7)

labels = dbscan.fit_predict(X_train_pca)

print("Unique labels:", np.unique(labels))
print("Number of points per cluster:", np.bincount(labels + 1))

for cluster in range(max(labels) + 1):
    mask = labels == cluster
    n_images = np.sum(mask)

    if n_images == 0:
        continue

    fig, axes = plt.subplots(
        1,
        n_images,
        figsize=(n_images * 1.5, 4),
        subplot_kw={'xticks': (), 'yticks': ()}
    )

    if n_images == 1:
        axes = [axes]

    for image, label, ax in zip(
        X_train[mask],
        y_train[mask],
        axes
    ):
        ax.imshow(
            image.reshape(image_shape),
            vmin=0,
            vmax=1
        )
        ax.set_title(
            people.target_names[label].split()[-1]
        )

    plt.show()

from sklearn.datasets import make_moons
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans, AgglomerativeClustering, DBSCAN
from sklearn.metrics.cluster import adjusted_rand_score
import numpy as np
import matplotlib.pyplot as plt

X, y = make_moons(
    n_samples=200,
    noise=0.05,
    random_state=0
)

# Rescale data
scaler = StandardScaler()
scaler.fit(X)
X_scaled = scaler.transform(X)

fig, axes = plt.subplots(
    1, 4,
    figsize=(15, 3),
    subplot_kw={'xticks': (), 'yticks': ()}
)

# Algoritma yang digunakan
algorithms = [
    KMeans(n_clusters=2),
    AgglomerativeClustering(n_clusters=2),
    DBSCAN()
]

# Random cluster assignment
random_state = np.random.RandomState(seed=0)
random_clusters = random_state.randint(
    low=0,
    high=2,
    size=len(X)
)

# Random assignment
axes[0].scatter(
    X_scaled[:, 0],
    X_scaled[:, 1],
    c=random_clusters,
    s=60
)

axes[0].set_title(
    "Random assignment - ARI: {:.2f}".format(
        adjusted_rand_score(y, random_clusters)
    )
)

# KMeans, Agglomerative, DBSCAN
for ax, algorithm in zip(axes[1:], algorithms):

    clusters = algorithm.fit_predict(X_scaled)

    ax.scatter(
        X_scaled[:, 0],
        X_scaled[:, 1],
        c=clusters,
        s=60
    )

    ax.set_title(
        "{} - ARI: {:.2f}".format(
            algorithm.__class__.__name__,
            adjusted_rand_score(y, clusters)
        )
    )

plt.show()

from sklearn.metrics.cluster import silhouette_score

X, y = make_moons(
    n_samples=200,
    noise=0.05,
    random_state=0
)

# Rescale data
scaler = StandardScaler()
scaler.fit(X)
X_scaled = scaler.transform(X)

fig, axes = plt.subplots(
    1, 4,
    figsize=(15, 3),
    subplot_kw={'xticks': (), 'yticks': ()}
)

# Random assignment
random_state = np.random.RandomState(seed=0)

random_clusters = random_state.randint(
    low=0,
    high=2,
    size=len(X)
)

axes[0].scatter(
    X_scaled[:, 0],
    X_scaled[:, 1],
    c=random_clusters,
    s=60
)

axes[0].set_title(
    "Random assignment: {:.2f}".format(
        silhouette_score(X_scaled, random_clusters)
    )
)

# Algoritma clustering
algorithms = [
    KMeans(n_clusters=2),
    AgglomerativeClustering(n_clusters=2),
    DBSCAN()
]

for ax, algorithm in zip(axes[1:], algorithms):

    clusters = algorithm.fit_predict(X_scaled)

    ax.scatter(
        X_scaled[:, 0],
        X_scaled[:, 1],
        c=clusters,
        s=60
    )

    ax.set_title(
        "{} : {:.2f}".format(
            algorithm.__class__.__name__,
            silhouette_score(X_scaled, clusters)
        )
    )

plt.show()

from sklearn.decomposition import NMF, PCA
from sklearn.cluster import KMeans
from sklearn.model_selection import train_test_split
import numpy as np
import matplotlib.pyplot as plt

# Membagi data menjadi data training dan testing
X_train, X_test, y_train, y_test = train_test_split(
    X_people, y_people,
    stratify=y_people,
    random_state=0
)

# NMF dengan 100 komponen
nmf = NMF(n_components=100, random_state=0)
nmf.fit(X_train)

# PCA dengan 100 komponen
pca = PCA(n_components=100, random_state=0)
pca.fit(X_train)

# K-Means dengan 100 cluster
kmeans = KMeans(n_clusters=100, random_state=0)
kmeans.fit(X_train)

# Rekonstruksi data menggunakan PCA
X_reconstructed_pca = pca.inverse_transform(
    pca.transform(X_test)
)

# Rekonstruksi data menggunakan K-Means
X_reconstructed_kmeans = kmeans.cluster_centers_[
    kmeans.predict(X_test)
]

# Rekonstruksi data menggunakan NMF
X_reconstructed_nmf = np.dot(
    nmf.transform(X_test),
    nmf.components_
)

fig, axes = plt.subplots(
    3, 5,
    figsize=(8, 8),
    subplot_kw={'xticks': (), 'yticks': ()}
)

fig.suptitle("Extracted Components")

for ax, comp_kmeans, comp_pca, comp_nmf in zip(
    axes.T,
    kmeans.cluster_centers_,
    pca.components_,
    nmf.components_
):
    ax[0].imshow(
        comp_kmeans.reshape(image_shape)
    )
    ax[1].imshow(
        comp_pca.reshape(image_shape),
        cmap='viridis'
    )
    ax[2].imshow(
        comp_nmf.reshape(image_shape)
    )

axes[0, 0].set_ylabel("kmeans")
axes[1, 0].set_ylabel("pca")
axes[2, 0].set_ylabel("nmf")

plt.show()

fig, axes = plt.subplots(
    4, 5,
    subplot_kw={'xticks': (), 'yticks': ()},
    figsize=(8, 8)
)

fig.suptitle("Reconstructions")

for ax, orig, rec_kmeans, rec_pca, rec_nmf in zip(
    axes.T,
    X_test,
    X_reconstructed_kmeans,
    X_reconstructed_pca,
    X_reconstructed_nmf
):
    ax[0].imshow(orig.reshape(image_shape))
    ax[1].imshow(rec_kmeans.reshape(image_shape))
    ax[2].imshow(rec_pca.reshape(image_shape))
    ax[3].imshow(rec_nmf.reshape(image_shape))

axes[0, 0].set_ylabel("original")
axes[1, 0].set_ylabel("kmeans")
axes[2, 0].set_ylabel("pca")
axes[3, 0].set_ylabel("nmf")

plt.show()

from sklearn.cluster import AgglomerativeClustering
import numpy as np

# extract clusters with ward agglomerative clustering
agglomerative = AgglomerativeClustering(n_clusters=10)

labels_agg = agglomerative.fit_predict(X_pca)

print("Cluster sizes agglomerative clustering: {}".format(
    np.bincount(labels_agg)
))

from sklearn.cluster import KMeans

# K-Means dengan 10 cluster
km = KMeans(n_clusters=10, random_state=0)

# Membuat label cluster
labels_km = km.fit_predict(X_pca)

print("Cluster sizes k-means: {}".format(
    np.bincount(labels_km)
))

from sklearn.metrics.cluster import adjusted_rand_score

print("ARI: {:.2f}".format(
    adjusted_rand_score(labels_agg, labels_km)
))

from scipy.cluster.hierarchy import dendrogram, ward
import matplotlib.pyplot as plt

linkage_array = ward(X_pca)

plt.figure(figsize=(20, 5))
dendrogram(
    linkage_array,
    p=7,
    truncate_mode='level',
    no_labels=True
)

plt.xlabel("Sample index")
plt.ylabel("Cluster distance")
plt.show()

from sklearn.decomposition import PCA
from sklearn.cluster import AgglomerativeClustering
import numpy as np
import matplotlib.pyplot as plt

# Gunakan 569 data yang sama dengan X_pca sebelumnya
X_cluster = X_train[:569]
y_cluster = y_train[:569]

# PCA
pca = PCA(n_components=100, random_state=0)
X_pca = pca.fit_transform(X_cluster)

print("Bentuk X_cluster:", X_cluster.shape)
print("Bentuk X_pca:", X_pca.shape)

# Agglomerative Clustering
agglomerative = AgglomerativeClustering(n_clusters=10)
labels_agg = agglomerative.fit_predict(X_pca)

print("Cluster sizes agglomerative clustering: {}".format(
    np.bincount(labels_agg)
))

n_clusters = 10

for cluster in range(n_clusters):
    mask = labels_agg == cluster

    fig, axes = plt.subplots(
        1, 10,
        subplot_kw={'xticks': (), 'yticks': ()},
        figsize=(15, 8)
    )

    axes[0].set_ylabel(np.sum(mask))

    images = X_cluster[mask]
    labels = y_cluster[mask]

    for image, label, ax in zip(images, labels, axes):
        ax.imshow(
            image.reshape(image_shape),
            vmin=0,
            vmax=1
        )
        ax.set_title(
            people.target_names[label].split()[-1],
            fontdict={'fontsize': 9}
        )

    plt.show()

agglomerative = AgglomerativeClustering(n_clusters=40)

labels_agg = agglomerative.fit_predict(X_pca)

print("Cluster sizes agglomerative clustering: {}".format(
    np.bincount(labels_agg)
))

n_clusters = 40

for cluster in [10, 13, 19, 22, 36]:
    mask = labels_agg == cluster

    fig, axes = plt.subplots(
        1, 15,
        subplot_kw={'xticks': (), 'yticks': ()},
        figsize=(15, 8)
    )

    cluster_size = np.sum(mask)

    axes[0].set_ylabel(
        "#{}: {}".format(cluster, cluster_size)
    )

    for image, label, cluster_label, ax in zip(
        X_cluster[mask],
        y_cluster[mask],
        labels_agg[mask],
        axes
    ):
        ax.imshow(
            image.reshape(image_shape),
            vmin=0,
            vmax=1
        )

        ax.set_title(
            people.target_names[label].split()[-1],
            fontdict={'fontsize': 9}
        )

    for i in range(cluster_size, 15):
        axes[i].set_visible(False)

    plt.show()

from sklearn.metrics.cluster import silhouette_score

print("Silhouette Score: {:.2f}".format(
    silhouette_score(X_pca, labels_agg)
))

from sklearn.metrics.cluster import silhouette_score

X, y = make_moons(
    n_samples=200,
    noise=0.05,
    random_state=0
)

scaler = StandardScaler()
scaler.fit(X)
X_scaled = scaler.transform(X)

fig, axes = plt.subplots(
    1, 4,
    figsize=(15, 3),
    subplot_kw={'xticks': (), 'yticks': ()}
)

random_state = np.random.RandomState(seed=0)
random_clusters = random_state.randint(
    low=0,
    high=2,
    size=len(X)
)

axes[0].scatter(
    X_scaled[:, 0],
    X_scaled[:, 1],
    c=random_clusters,
    cmap=mglearn.cm3,
    s=60
)

axes[0].set_title(
    "Random assignment: {:.2f}".format(
        silhouette_score(X_scaled, random_clusters)
    )
)

algorithms = [
    KMeans(n_clusters=2),
    AgglomerativeClustering(n_clusters=2),
    DBSCAN()
]

for ax, algorithm in zip(axes[1:], algorithms):
    clusters = algorithm.fit_predict(X_scaled)

    ax.scatter(
        X_scaled[:, 0],
        X_scaled[:, 1],
        c=clusters,
        cmap=mglearn.cm3,
        s=60
    )

    ax.set_title(
        "{} : {:.2f}".format(
            algorithm.__class__.__name__,
            silhouette_score(X_scaled, clusters)
        )
    )

plt.show()